# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Spotless Format Fixer with Gradle
# Controls when the action will run. Triggers the workflow on push or pull request
# events
on:
  workflow_run: 
    workflows: [Spotless format check with Gradle]
    types: completed
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  on-failure:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Apply spotless
        run: ./gradlew spotlessApply
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Formatted code using spotless.'
        
      
